version: '3'
services:
  mongo:
    build: Docker/mongo
    volumes:
      - "./mongo/db:/data/db"
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  flask:
    build:
      context: .
      dockerfile: Docker/flask/Dockerfile
    links:
      - mongo
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - .:/home/web
    environment:
      DOCKER: 'True'
  nginx:
      build: Docker/nginx
      links:
        - flask
      volumes:
        - "./nginx/log:/var/log/nginx"
        - "./:/usr/share/nginx/html"
      ports:
        - "80:80"
        - "8080:8080"
        - "443:443"
      restart: always